// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Models;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 25000m,
                            ProductName = "IPhone 11"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = false,
                            Price = 27000m,
                            ProductName = "IPhone 12"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = true,
                            Price = 45000m,
                            ProductName = "IPhone 13"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = false,
                            Price = 65000m,
                            ProductName = "IPhone 14"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
